### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by Muzammil2008** [Muzammil2008/New-Year-Count-Down#1]
My timer is not coming

**Comment by LatentM** [comment]
Send link

**Comment by Muzammil2008** [comment]
https://muzammil2008.github.io/New-Year-Count-Down/index.html

**Comment by Muzammil2008** [comment]
there it is

**Comment by LatentM** [comment]
var countDate = new Date('Jan 1, 2020 00:00:00').getTime();

should be

var countDate = new Date().getTime();

**Comment by Muzammil2008** [comment]
ok

**Comment by Muzammil2008** [comment]
![Screenshot from 2020-12-15 19-24-27](https://user-images.githubusercontent.com/70088433/102223827-35848700-3f0b-11eb-8b32-ea8299d4f4a5.png)

**Comment by Muzammil2008** [comment]
**This is the code**


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>New Year Countdown Clock</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<div class="container">
		<h2><span>Countdown to New Year</span> 2021</h2>
		<div class="countdown">
			<div id="Day">NA</div>
			<div id="Hour">NA</div>
			<div id="Minute">NA</div>
			<div id="Second">NA</div>
		</div>
	</div>
	<script type="text/javascript">
	var countDate = new Date('Jan 1, 2021 00:00:00').getTime();

	function newYear(){
		var now = new Date().getTime();
		gap = countDate - now;

		var second = 1000;
		var minute = second * 60;
		var hour = minute * 60;
		var day = hour * 24;

		var d = Math.floor(gap / (day));
		var h = Math.floor((gap % (day)) / (hour));
		var m = Math.floor((gap % (hour)) / (minute));
		var s = Math.floor((gap % (minute)) / (second));

		document.getElementById('day').innerText =d;
		document.getElementById('hour').innerText = h;
		document.getElementById('minute').innerText = m;
		document.getElementById('second').innerText = s;
	}

	setInterval(function() {
		newYear();
	},1000)
	</script>
</body>
</html>

**Comment by Muzammil2008** [comment]
I have completed it see
https://muzammil2008.github.io/New-Year-Count-Down/index.html
![Screenshot from 2020-12-15 19-56-22](https://user-images.githubusercontent.com/70088433/102227520-ab8aed00-3f0f-11eb-8740-d69b9bfd1854.png)

**Comment by Muzammil2008** [comment]
Solved
